### ISSUE TITLE
Deixar menu funcional

### ISSUE THREAD

**Issue by KastroWalker** [acaverna/site-oficial#12]
Adicionar função de hover ao clicar nos links do menu.

**Comment by karennovaes** [comment]
Eu quero resolver este problema.

**Comment by pachicodes** [comment]
RESOLVA!

**Comment by KastroWalker** [comment]
Essa issue foi resolvida com o [PR #17](https://github.com/acaverna/site-oficial/pull/17), por esse motivo vou finalizar a issue.
